- charts/backstage/Chart.yaml
- charts/backstage/templates/serviceaccount.yaml
Fixes indentation issues with labels and annotations in the service account template.
The following values.yaml
```yaml
backstage:
image:
registry: repo
repository: backstage
tag: master
serviceAccount:
create: true
annotations:
eks.amazonaws.com/role-arn: "ROLE"
eks.amazonaws.com/sts-regional-endpoints: "true"
labels:
nginx.ingress.kubernetes.io/rewrite-target: "/"
nginx.ingress.kubernetes.io/ssl-redirect: "false"
```
Now returns:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: 
namespace: default
labels:
app.kubernetes.io/component: backstage
nginx.ingress.kubernetes.io/rewrite-target: /
nginx.ingress.kubernetes.io/ssl-redirect: "false"
annotations:
eks.amazonaws.com/role-arn: ROLE
eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: true
```
> Fix indentation for serviceAccount labels and annotations

- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/release.yml
- .github/workflows/test.yml
- charts/backstage/Chart.yaml
- charts/backstage/chart_schema.yaml
- charts/backstage/ci/ci-values.yaml
- charts/backstage/values.yaml
- ct-install.yaml
- ct.yaml
Resolves: #6 
Using [janus-idp/redhat-backstage-build](https://github.com/janus-idp/redhat-backstage-build) as deployment image, since I don't know about any other vanilla image out there... I think we want to change this to an upstream image if possible.
> chore: Add CI tests

- README.md
- charts/backstage/Chart.yaml
- charts/backstage/ci/ci-values.yaml
- charts/backstage/values.yaml
This PR sets default image to `ghcr.io/backstage/backstage:latest` (removes CI override and sets it directly in the default values)
Resolves: #12 #16 
Image provided by @Rugvip https://github.com/backstage/charts/pull/8#discussion_r1042045587
> Default to upstream image

- README.md
- charts/backstage/Chart.yaml
- charts/backstage/templates/ingress.yaml
- charts/backstage/values.yaml
Adds TLS Configuration for Ingress. Closes: https://github.com/backstage/charts/issues/2
- [N/A] JSON Schema generated.
Have added the variables to the Values file and the `README.md` but we don't use `helm-docs` auto-generation at the moment. There was an open issue on this on the [old backstage chart repo](https://github.com/vinzscam/backstage-chart/issues/3) but we never actually implemented it. I feel we should raise a separate issue for this and track it separately.
Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>
> feat: Adds TLS for Ingress

- charts/backstage/Chart.yaml
- charts/backstage/templates/ingress.yaml
- charts/backstage/values.yaml
Ingress annotations were a string instead of a proper dictionary
n/a
If rendered with the default values as:
```sh
helm template --set backstage.image.registry=registry,backstage.image.repository=repo/image,backstage.image.tag=latest,ingress.enabled=true .
```
The ingress was rendered as:
```yaml
...
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: release-name-backstage
namespace: "tumido"
labels:
app.kubernetes.io/name: backstage
helm.sh/chart: backstage-0.5.2
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: backstage
annotations:
{ "nginx.ingress.kubernetes.io/rewrite-target": "/", "nginx.ingress.kubernetes.io/ssl-redirect": "false" }
...
```
After the change the Ingress template renders:
```yaml
...
apiVersion: …
```
> fix: Ingress annotations format

- charts/backstage/Chart.yaml
- charts/backstage/templates/ingress.yaml
Introduced recently in the TLS section is the {{- end -}} where we suppress the newline. This causes the rules to end up on the same line as the previous section and would break the schema and get something like spec:rules: which is invalid
Changes the {{- end -}} for the TLS section of the ingress to not suppress the newline
Fixes: https://github.com/backstage/charts/issues/21
> Bugfix: Fix ingress error causing spec and Rules to be on single line

- LICENSE
- NOTICE
I think we should add a license to this repository. Let's align it with the [Backstage license](https://github.com/backstage/backstage/blob/master/LICENSE) as well as [Bitnami charts](https://github.com/bitnami/charts/blob/main/LICENSE.md) (because of chart dependency, it's not necessary but nice to have).
I'm not entirely sure of the legal process for this but I think it would be nice if all current contributors can approve of the license choice.
cc @vinzscam @nikolaik @froblesmartin @cmoulliard @ChrisJBurns
> chore: Add license

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- charts/_templates.gotmpl
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
@ChrisJBurns [comment](https://github.com/backstage/charts/pull/17#discussion_r1042594472) made me realize that we're missing a properly set up `helm-docs`. This should make contributions easier. I'm also adding a [pre-commit hook](https://pre-commit.com/) for those who use it so you don't ever have to worry about forgetting stale README.
Future README changes for the chart itself should be done against `charts/backstage/README.md.gotmpl`.
> docs: Use helm-docs with a proper template

- .gitignore
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
- Adds Security Context for Pod and Containers. Closes: https://github.com/backstage/charts/issues/3
- Adds `.gitignore` to avoid chart dependencies and their `.tgz`'s being added and to ignore common MacOS files
- [N/A] JSON Schema generated.
Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>
> feat: adds securityContexts (pod & container)

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
Adds support for setting requests and limits on the backstage deployment such that folks can execute to their desired best practices on resource consolidation.
https://github.com/backstage/charts/issues/26
Looked over my local developer deployment that has a number of added plugins and a few charts etc and what the resource limits were. Set memory fairly high comparatively but cpu should be fully in line.
> Feature: Resource Limits for backstage container

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/templates/serviceaccount.yaml
Migrate toYaml to reusable partial
> Migrate toYaml to partial

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
Adds support for providing extra containers and initContainers to the backstage Deployment
> Added support for extraContainers and initContainers

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
- charts/backstage/ci/appConfig-values.yaml
- charts/backstage/ci/extraVolumes-values.yaml
- charts/backstage/templates/app-config-configmap.yaml
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
This PR was originally started at: https://github.com/vinzscam/backstage-chart/pull/24
As it was discussed a little bit at https://github.com/vinzscam/backstage-chart/issues/4:
I think it would be nice to give the possibility to define an extra app config file in the values.yaml, which then creates a ConfigMap automatically, mounts it and uses it in the config.
Please, let me know your thoughts, and if there is anything I should improve or change. :)
The problem with the current approach is that the ConfigMap needs to be provided externally from this Helm chart. It is not a big deal, but I think it would be nice to provide both things, generating the ConfigMap in the Helm chart itself, and also allowing us to define the config in the values.yaml file. In the end the idea of the …
> feat: define extra app config which generates ConfigMap

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/service.yaml
- charts/backstage/values.yaml
Enable the ability to specify the service target port to avoid hardcoded value
> Enable the ability to specify the service target port

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
This allows automatic rolling deployments on config changes like described in  https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
Augments the functionality added in https://github.com/backstage/charts/pull/23
> feat: Annotate deployment with app config checksum 

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/_helpers.tpl
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/templates/serviceaccount.yaml
- charts/backstage/values.yaml
It is currently not possible to use an existing serviceAccount without creating it.
This feature provides the ability to do that. It is inspired by bitnami charts, such as https://github.com/bitnami/charts/blob/91fca1180126322b3d9ddc748ebe48de53f139fe/bitnami/postgresql/values.yaml#L1169
> feat: allow using existing serviceAccount

- .github/workflows/release.yml
- cr.yaml
Start using the flag introduced in https://github.com/helm/chart-releaser/releases/tag/v1.5.0 which relies on GitHub to generate release notes automatically.
Resolves #24
> chore: Generate release notes

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
Add optional tolerations to the chart.
Not much to add here, it lets you choose which nodes in the cluster the containers are deployed to.
This is required in some cluster configurations.
> Tolerations option

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
We use them in combinations with KIAM to allow the pod to assume a IAM role
> feat: allow setting podAnnotations

- charts/backstage/Chart.lock
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/servicemonitor.yaml
- charts/backstage/values.yaml
Backstage instances with the [Prometheus /metrics endpoint](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/prometheus-metrics.md) configured can set `metrics.serviceMonitor.enabled` to allow prometheus to scrape it's metrics
Disabled by default.
Example diff:
```diff
backstage, backstage, ServiceMonitor (monitoring.coreos.com) has been added:
+ # Source: backstage/templates/servicemonitor.yaml
+ apiVersion: monitoring.coreos.com/v1
+ kind: ServiceMonitor
+ metadata:
+   name: backstage
+   namespace: "backstage"
+   labels:
+     app.kubernetes.io/name: backstage
+     helm.sh/chart: backstage-0.16.0
+     app.kubernetes.io/instance: backstage
+     app.kubernetes.io/managed-by: Helm
+     app.kubernetes.io/component: backstage
+ spec:
+   namespaceSelector:
+ …
```
> feat: Add ServiceMonitor for Prometheus operator

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/_helpers.tpl
- charts/backstage/templates/backstage-deployment.yaml
When using the `global` config in the `values.yaml` to configure a (proxy) registry and the necessary image pull secret, the registry is used in the `deployment.yaml` template, but the image pull secret is not. This leads to a failing deployment, because the image cannot be pulled. 
Render the image pull secret from the global config in the deployment in addition to the secret configured there explicitly.
None
Bitnamis `common` chart provides a helper `common.images.renderPullSecrets`:
https://github.com/bitnami/charts/blob/f13df7b00f38e5fce67eab7a1b78afb0b064344e/bitnami/common/templates/_images.tpl#L54-L80
> bugfix: Render globally configured image pull secrets in deployment template

- .github/workflows/release.yml
https://github.com/backstage/charts/pull/61 Probably introduces a bug to our CI. `cosign` now promts for confirmation which breaks our release pipeline (see https://github.com/backstage/charts/actions/runs/4404080373/jobs/7713244708 )
This should be fixed by adding a [`--yes|-y`](https://github.com/sigstore/cosign/blob/3238ae9dd7289659bc3dbe36d9372faafb59990f/doc/cosign_sign.md?plain=1#L100) param to `cosign sign` command.
N/A
N/A
Doesn't apply
> chore(ci): Fix cosign confirmation prompts

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/service.yaml
- charts/backstage/values.yaml
A small PR enabling `Service`'s port name to be configured through `values.yaml`. Default value matches the previously hardcoded name.
N/A
N/A
> feat: Change Service port name from hardcoded to a value

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
Allow configuring the `spec.replicas` in the backstage deployment, for HA we need more than 1.
> feat: allow setting Deployment replicas count via values

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
> add nodeSelector to deployment template

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.yaml
In addition to `backstage.podAnnotations` and `commonAnnotations` we want to have something specific to the `Deployment` resource. In case we want to annotate `Deployment` the `commonAnnotations` value is too noisy and `backstage.podAnnotations` is not really being set on the `Deployment` itself.
Other resources deployed by this chart have their own specific chart value for annotations (`service.annotations`, `ingress.annotations`, etc...).
N/A
@backstage/helm-charts and @backstage/helm-charts-maintainers wdyt? Does it make sense to have yet another annotation value in the chart? Should I propagate this `backstage.annotations` value to the pod as well?
> feat: add additional annotations to Deployment

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
Implements JSON schema for the chart and enriches `Chart.yaml` with additional metadata
Resolves #14 
Schema was written manually since there's no automation available as far as I know.
Schema includes remote references to:
- Bitnami/PostgreSQL's [`values.schema.json`](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.schema.json)
- https://kubernetesjsonschema.dev (outdated but sufficient)
- `io.k8s.api.core.v1.Container`
- `io.k8s.api.core.v1.EnvVar`
- `io.k8s.api.core.v1.VolumeMount`
- `io.k8s.api.core.v1.Volume`
- `io.k8s.api.core.v1.ResourceRequirements`
- `io.k8s.api.core.v1.SecurityContext`
- `io.k8s.api.core.v1.Toleration`
- `io.k8s.api.networking.v1.NetworkPolicyEgressRule`
Additionally, I've fixed:
- a few broken links in `values.yaml` references to …
> feat: add json schema for the chart

- README.md
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
Adds a disclaimer about the Backstage image being deployed not being customizable/customized.
Resolves #67
> chore: add disclaimer about Backstage customization

- charts/backstage/Chart.yaml
- charts/backstage/README.md
The latest kubernetes version restriction I've found is that our chart uses `Ingress` resource which went GA in `1.19.0`.
N/A
> chore: set required kubeVersion because of Ingress resource

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
changing the type of extraEnvVarsSecrets to string as providing a valid secret name as an array item is resulting in the error backstage.extraEnvVarsSecrets.0: Invalid type. Expected: object, given: string
```
extraEnvVarsSecrets:
- <secret-name>
```
> Change extraEnvVarsSecrets item type to string

- .github/workflows/release.yml
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
- charts/backstage/artifacthub-repo.yml
Close the loop on ArtifactHub by verifying the published chart ownership.
https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support
Resolves #41
> chore: verify ArtifactHub ownership as OCI artifact

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
I was too quick to merge #102 and noticed this typo right after clicking the merge button. I apologize, it's a copy-paste error from when I was enabling the same in our vendor-specific chart in Janus IDP.
> chore: fix artifacthub badge

- charts/backstage/Chart.lock
- charts/backstage/Chart.yaml
- charts/backstage/README.md
Update our dependencies. Since they release a breaking change, we should probably do the same.
BREAKING CHANGE: `bitnami/postgres` updates default PostgreSQL image 14->15
Chart functions should not be impacted. All should behave as expected. We can't stay on outdated dependencies forever...
> feat: upgrade dependencies `bitnami/*`

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
When using chart values schema I've noticed I made a mistake in https://github.com/backstage/charts/pull/92 and instead of nesting all `properties` under the `properties` key, some were left under the schema root. This doesn't resolve as a valid property and therefore it makes schemas of affected keys unusable.
Affected keys:
- `postgresql`
- `serviceAccount`
- `metrics`
N/A
Git diff looks a bit weird, however all changeset is just about nesting affected properties one level deeper aka "add 4 spaces and move a coma".
> fix(schema): all properties should be nested under `properties` key

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
Providing the value for `backstage.appConfig` as a string does technically work, but is not allowed by the schema.
Allow key `backstage.appConfig` to be of type `object` or `string`.
None
The template `app-config-configmap.yaml` uses the `common.tplvalues.render` helper function from the bitnami common chart.
https://github.com/backstage/charts/blob/b1d86d306a066282ceba5206ba8267f78fbbb464/charts/backstage/templates/app-config-configmap.yaml#L7-L8
That helper function supports both, `string`-type and `object`-type values.
https://github.com/bitnami/charts/blob/35bc6b1d5d87dfc3875ed09a45bffd2bddc9ee6d/bitnami/common/templates/_tplvalues.tpl#L2-L13
> Allow appConfig to be provided as a string

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
Add the labels defined in `podLabels` to pods managed by the deployment object.
Fixes #110 
n/a
> fix: Add pod labels to pod spec inside deployment object

- charts/backstage/Chart.lock
- charts/backstage/Chart.yaml
- charts/backstage/README.md
updates  `bitnami-common` and `postgresql` charts to latest versions
> feat: update bitnami-common to 2.10.0 and postgresql to 12.10.0

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/app-config-configmap.yaml
- charts/backstage/templates/backstage-deployment.yaml
Scope the name of generated config map to reflect potential name overrides, currently it is impossible to install 2 instances in a single namespace.
N/A
> bug: fix name of appConfig configmap

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/networkpolicy-egress.yaml
- charts/backstage/templates/networkpolicy.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
Added support for Ingress and Egress Network Policies
#91
> Added support for NetworkPolicies

- .helmignore
- .pre-commit-config.yaml
- .pre-commit/jsonschema-dereference.py
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
Air-gapped environments should be supported. The only blocker we had here were remote references in `values.schema.json`. While these remote references reduce maintenance and repetition on our side, it requires helm to query for those references when processing values file.
Therefore to keep the benefits of remote references and allow consumers to install in air-gapped environment, I've added a small pre-commit script allowing us to treat the `values.schema.json` with remote references as a kind of template. I've moved our current `values.schema.json` to `values.schema.tmpl.json`. This template is dereferenced via pre-commit and the resulting schema with expanded references is stored as `values.schema.json`. This schema is then understood by Helm and can be used in air-gapped …
> feat: values.schema.json to support air-gapped environments

- .github/workflows/release.yml
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
In the values schema, the references to `kubernetes` definitions point to a rather old and obsolete schema (not updated since 3 years): https://github.com/instrumenta/kubernetes-json-schema
This PR proposes to switch to the following fork of the previous repository, which provides up-to-date `kubernetes` schemas: https://github.com/yannh/kubernetes-json-schema#readme
This will allow using recent Kubernetes features like [Generic Ephemeral Volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) 
- Fixes #?
Please make sure that the following steps are complete:
> fix: Use an up-to-date `kubernetes` schema

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Adds support to reference external configmaps in the backstage deployment. This is useful if external configuration like e.g. the Postgres database connection values are required from a configmap managed elsewhere.
It's a common pattern that is implemented as standard in all Bitnami Charts. See https://github.com/bitnami/charts/blob/main/template/README.md?plain=1#L27
I hope I managed to run all commands currently (helm-docs and the python script). A bit more info in the checklist would be helpful (e.g. to check .pre-commit-config.yaml or even the exact commands to run).
> Add support for external configmaps using backstage.extraEnvVarsCM

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/ingress.yaml
In some cases it may be useful to allow `ingress.host` to be templated - for example if you want to reuse the same value in `backstage.appConfig`. In scenarios where Backstage chart is used as a subchart the only way to properly propagate templated values is through `global` scope (you can't reference `ingress.host` outside of the subchart). This PR should add support for such scenarios:
```yaml
global:
foo: foo.bar
ingress:
host: '{{ .Values.global.foo }}'
enabled: true
```
> feat: allow for ingress.host templating

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/_helpers.tpl
Our dependency - bitnami/postgresql chart has an option to configure `auth` via `global` scope variables. We do not consider that option when we infer secret name and key for the Backstage deployment volume mounts.
This PR adds support for:
1. `.Values.global.postgresql.auth.existingSecret` which overrides `.Values.postgresql.auth.existingSecret`
2. `.Values.global.postgresql.auth.secretKeys.userPasswordKey` which overrides `.Values.postgresql.auth.secretKeys.userPasswordKey` and (either of these) gets applied only if 
`.Values.global.postgresql.auth.existingSecret` or `.Values.postgresql.auth.existingSecret` is defined
I'm using `()` chaining Helm `?.` pipeline notation/workaround so I can avoid declaring those variables as `''` in `values.yaml`
> fix: honor .global.postgresql.auth values

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
I've noticed we have a `backstage.debug` flag and it does nothing. It's never used in any of the templates.
Instead of inventing our own solution to a "debug" flag, I think we should just get rid of it and let people use the officially documented https://backstage.io/docs/local-dev/debugging/ env variables.
> fix: remove unused backstage.debug flag

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
Signed-off-by: smcavallo <smcavallo@hotmail.com>
There are no functional changes to the chart.  The current CI build is failing.
It is due to newer properties being added when generating the json schema for values which are part of the api extensions.
The only change made in this PR is to regenerate the values schema.
Ex. `python3 .pre-commit/jsonschema-dereference.py`
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X ] JSON Schema generated.
> fix: latest schema gen

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Signed-off-by: smcavallo <smcavallo@hotmail.com>
Adds support for pod affinity
output of `helm template --values=values.yaml .` before and after adding this feature is exactly the same
output after defining affinity in values works as expected:
``` 
annotations:
checksum/app-config: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
spec:
serviceAccountName: default
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: my-nodegroup
operator: In
values:
- backstage
volumes:
```
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X ] Variables are documented in the `values.yaml` and added to the README.md. The [helm-docs](https://github.com/norwoodj/helm-docs) utility can be …
> feat: add support for pod affinity

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/ingress.yaml
The `ingress.host` value is supported to use helm templating when used in the rules section of the `Ingress` resource, but when enabling TLS, it uses the host value un-rendered so it breaks if using template syntax.
This change renders the `ingress.host` for all uses, along with `ingress.tls.secretName` to make it more flexible as well.
> fix: render ingress host also when using tls.

- .github/workflows/automate_stale.yml
Adding a stale workflow to help maintain repository health and streamline maintenance tasks, aligning with [backstage/backstage](https://github.com/backstage/backstage).
> Add stale workflow

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
- charts/backstage/values.schema.json
chore: update chart readme to recommend newer versions of Helm (not 3.2)
Signed-off-by: Nick Boldt <nboldt@redhat.com>
For context:
> The documentation for deploying RHDH is missing information for both upstream (backstage/chart) and backstage-showcase docs regarding the required Helm CLI version. This has led to parsing errors during deployment, particularly with Helm 3.6.
> As per the discussion with [Tomas Kral](https://github.com/kadel) suggested fix: 
* To include a section in both upstream ([backstage/chart](https://github.com/backstage/charts)) and 
* [backstage-showcase](https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/helm-chart.md) docs  specifying the minimum required Helm CLI version for deployment. 
The recommended version is  last stable version (3.13) …
> chore: update chart readme to recommend newer versions of Helm (not 3.2)

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/app-config-configmap.yaml
fix: add namespace to configmap = .Release.Namespace; bump chart version to 1.9.3; update/regen docs
Signed-off-by: Nick Boldt <nboldt@redhat.com>
Based on proposed changes in #176 from @IronMage but with DCO fixed and more complete [pre-commit hooks](https://github.com/backstage/charts/blob/main/.pre-commit-config.yaml) applied.
```
Run standard RH pre-commit checks........................................Passed
Helm Docs................................................................Passed
jsonschema-dereference...................................................Passed
```
Ref: https://issues.redhat.com/browse/RHIDP-2170
> fix: add namespace to configmap = .Release.Namespace; bump chart version to 1.9.3; update/regen docs

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/ingress.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
These changes convert `ingress.path` as a configurable property. The change is needed for the deployments in a specific path instead of the base domain.
Closes #195
> feat(ingress): add path as property configurable

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/ci/image-digest-values.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Add option to pass image tag by digest (i.e. `sha256:xxx`) instead of image tag. This makes use of already existing support in the [bitnami common templates](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_images.tpl).
Apologies as this is just updating the `values.yaml` file I haven't opened an issue.
This is a common issue that gets flagged when auditing kubernetes manifests with tooling like `trivy` or `checkov`. If you need more detail let me know and I can add some examples to the PR description.
> feat(backstage): option to pass in image by digest

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/ci/ingress-extraHosts-values.yaml
- charts/backstage/ci/ingress-values.yaml
- charts/backstage/templates/ingress.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Adds `ingress.extraHosts` and `ingress.extraTls` which allows you to add extra `host` and `tls` items to the generated Ingress resource.
We run Backstage in EKS and are currently adding a [condition](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#conditions) annotation in the Ingress to configure the AWS ALB with an extra hostname. The downside with this approach is that we have to specify the AWS ACM certificate ARN:s for the domains (we loose the certificate discovery functionality).
There are other workarounds as well (e.g. using `extraDeploy` to create multiple Ingress resources), but having native support for multiple hosts in the Helm chart would simplify our life a bit.
> feat: add support for multiple hosts and tls configurations in ingress

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/ci/topologySpreadConstraints-values.yaml
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Adds the ability to use Topology Spread Constraints (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#pod-topology-spread-constraints).
None
Default behaviour remains unchanged. Nothing removed.
The chart currently supports `affinity` rules, but `topologySpreadConstraints` give finer control - see https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#comparison-with-podaffinity-podantiaffinity.
In my specific use-case, https://kubernetes.io/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/#kep-3243-respect-pod-topology-spread-after-rolling-upgrades allows reuse of nodes during the rollout of a deployment, but I still end up with an appropriate spread of pods at the end. Similar changes are coming to affinity in k8s 1.31, …
> Add option to set Topology Spread Constraints, rather than just Affinity

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Adds support for hostAliases
Builds upon and supersedes #207
> Add support for hostAliases

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
Allow chart users to specify extra backend container ports.
This is especially useful for monitoring.
This resolves #236
> feat: allow extra ports to be added to the backend service

- README.md
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
- charts/backstage/ci/service-dualstack-ip-family-values.yaml
- charts/backstage/templates/service.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
This PR allows users to configure the `ipFamilyPolicy` and `ipFamilies` of the Kubernetes Service.
By default, Kubernetes Services are created to work only on the IPv4 stack.
People on a dual-stack network should be able to specify the policy they want.
See https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services for reference.
&mdash;
&mdash;
> feat: Allow configuring the Service IP Family policy to make it dual-stack

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/pdb.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
> feat: Add PDB

- .codespellrc
- .github/workflows/spellcheck.yaml
- .pre-commit-config.yaml
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
I noticed we had a couple of incorrect spellings lying around, so thought it would be a good idea to build a spellcheck into the PR workflow checks. Have also added this to the `pre-commit` config too so folks can run these checks locally before they put a PR up.
> feat: adds codespell action to ensure correct spelling

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/ci/autoscaling-values.yaml
- charts/backstage/templates/backstage-deployment.yaml
- charts/backstage/templates/hpa.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.schema.tmpl.json
- charts/backstage/values.yaml
This PR adds support for autoscaling using an Horizontal Pod Autoscaler, to be able to automatically scale the number of replicas up/down based on resource (CPU/Mem) usage.
See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ and https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
&mdash;
Deploy the Chart with `backstage.autoscaling.enabled=true`.
You should see a new HPA resource will be created.
> feat: Support autoscaling via HPA
